-- Grades seed data
INSERT INTO grades (code, name) VALUES
('DCA', 'Deputy Chief Accountant'),
('PBS', 'Principal Biomedical Scientist'),
('DCBS', 'Deputy Chief Biomedical Scientist'),
('HA', 'Hospital Administrator'),
('MEDSUP', 'Medical Superintendent'),
('SMDO', 'Senior Midwifery Officer'),
('MDO', 'Midwifery Officer'),
('MO', 'Medical Officer'),
('SMO', 'Senior Medical Officer'),
('CRA', ''),
('SPA', 'Senior Physician Assistant'),
('PPA', 'Principal Physician Assistant'),
('DCPA', 'Deputy Chief Physician Assistant'),
('PNO', 'Principal Nursing Officer'),
('SP', 'Senior Pharmacist'),
('SMA', 'Senior Mortuary Attendant'),
('ACC', 'Accountant'),
('SACC', 'Senior Accountant'),
('PACC', 'Principal Accountant'),
('CHN', 'Community Health Nurse'),
('SCHN', 'Senior Community Health Nurse'),
('PCHN', 'Principal Community Health Nurse'),
('EN', 'Enrolled Nurse'),
('SEN', 'Senior Enrolled Nurse'),
('PEN', 'Principal Enrolled Nurse'),
('BS', 'Biomedical Scientist'),
('SBS', 'Senior Biomedical Scientist'),
('SN', 'Staff Nurse'),
('SSN', 'Senior Staff Nurse'),
('NO', 'Nursing Officer'),
('SNO', 'Senior Nursing Officer'),
('DDNS', 'Deputy Director of Nursing Services'),
('SM', 'Staff Midwife'),
('SSM', 'Senior Staff Midwife'),
('SITM', 'Senior IT Manager'),
('SNTO', 'Senior Nutrition Technical Officer'),
('FT', 'Field Technician'),
('SLA', 'Senior Laboratory Assistant'),
('TOH', 'Health Promotion Officer'),
('STOL', ''),
('CO', 'Catering Officer'),
('PD', 'Principal Driver'),
('SDT', 'Senior Dental Technician'),
('STN', 'Stenographer'),
('SPO', 'Senior Procurement Officer'),
('SO', 'Store Officer'),
('SSO', 'Senior Store Officer'),
('PA', 'Physician Assistant'),
('P', 'Pharmacist'),
('ACO', 'Account Officer'),
('BA', 'Biostatistics Assistant'),
('HO', 'Hospital Orderly'),
('ITM', 'IT Manager'),
('RD', 'Radiographer'),
('PT', 'Pharmacy Technician'),
('FO', 'Finance Officer'),
('LA', 'Laboratory Assistant'),
('HAS', 'Hospital Administration Support'),
('TA', ''),
('LB', 'Laborer'),
('LD', 'Laundryman/Woman'),
('DA', 'Dispensary Assistant'),
('RA', 'Record Assistant'),
('RC', 'Revenue Collector')
ON DUPLICATE KEY UPDATE name = VALUES(name);
