name: Deploy PHP App to EC2

on:
  push:
    branches: [ "main" ]  # or master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_DEPLOY_PASSPHRASE: ${{ secrets.EC2_DEPLOY_PASSPHRASE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          extensions: mbstring, xml, bcmath, intl

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_HOST }}
          username: ubuntu
          key: ${{ env.EC2_SSH_KEY }}
          passphrase: ${{ env.EC2_DEPLOY_PASSPHRASE }}
          script: |
            cd /var/www/basturms
            git pull origin main
            composer install
            composer dump-autoload -o           
            sudo systemctl restart apache2
            sudo systemctl restart mysql
           
